<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="bootstrap.min.css" />
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

    <link rel="icon" href="img/3.png" />

    <title>Document</title>
</head>
<body>
      <div class="sign">
    <h1>Créer un nouveau compte </h1>
    
        <legend>C’est rapide et facile.</legend>
        <form method="POST" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?>" method="post">
  <div class="form-group">
    
    <label  for="nom">Nom & Prénom</label>
    
    <input type="text" class="form-control" name="username" placeholder="Foulen Ben Foulen 123"  required value="<? = $_POST['username'] ?? '' ?>">
    <span class="text-danger"><?php if (isset($username_error)) echo $username_error?></span>
  </div>
    
 <div class="form-group">
    <label for="pseudo">Email</label>
    <input type="e-mail" class="form-control" name="email" value="<? = $_POST['email'] ?? '' ?>"  required placeholder="foulenbenfoulen@foulen.com">
    <span class="text-danger"><?php if (isset($email_error)) echo $email_error?></span>
  </div>
   <div class="form-group">
    <label for="mdp">Mot de passe</label>
    <input type="password" class="form-control" name="pass" placeholder="Mot de passe" >
    <span class="text-danger"><?php if (isset($pass_error)) echo $pass_error?></span>
  </div>
  <div class="form-group">
    <label for="mdp">Confirmer Mot de passe</label>
    <input type="password" class="form-control" required name="cpass" placeholder="Confirmer Mot de passe">
    <span class="text-danger"><?php if (isset($cpass_error)) echo $cpass_error?></span>
  </div>
  <div class="form-group">
    <label for="Adresse">Adresse</label>
    <input type="text" class="form-control" name="adresse" required placeholder="Adresse">

  </div>
  <div class="form-group">
    <label for="Adresse">Téléphone</label>
    <input type="number" class="form-control" name="tel" required placeholder="Num téléphone">
   
  </div>

  <button class="btn btn-danger" name="signup" type="submit"> Submit</button>
  </div>
</body>
</html>